package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/ravikumarve/ControlPlane/mcp-guard/internal/templates"
)

var templateFlag string

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a default mcp-guard.yaml config file",
	Long:  `Creates a starter mcp-guard.yaml in the current directory with example policies and default settings.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		path := "mcp-guard.yaml"
		if len(args) > 0 {
			path = args[0]
		}

		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s already exists — remove it first or specify a different path", path)
		}

		var content string
		if templateFlag != "" {
			tmpl, ok := templates.Get(templateFlag)
			if !ok {
				return fmt.Errorf("unknown template %q — available: %v", templateFlag, templates.List())
			}
			content = tmpl
		} else {
			content = `# mcp-guard.yaml — Generated by 'mcp-guard init'
version: "1"

proxy:
  mode: stdio          # stdio | tcp | both
  listen: ":8443"      # TCP listen address (TCP mode)
  upstream: ""          # TCP upstream target (TCP mode)

policies:
  - name: allow-read-only
    match:
      identity: "*"
      tools: ["read_*", "search_*", "get_*", "list_*"]
    action: allow
    rate_limit: 100/min

  - name: block-dangerous
    match:
      tools: ["drop_table", "rm_rf", "exec_shell", "payout"]
    action: block
    alert: true

  - name: payment-approval
    match:
      tools: ["execute_payout", "refund", "transfer"]
    action: hitl
    constraints:
      max_amount: 500

schema_pinning:
  enabled: true
  mode: block          # block | warn | log
  store: ".mcp-guard/pins.json"

audit:
  path: "/var/log/mcp-guard/audit.jsonl"
  hmac_key: "${MCP_GUARD_HMAC_KEY}"
  rotation: 100MB

hitl:
  webhook_url: "${SLACK_WEBHOOK_URL}"
  timeout: 5m

alert:
  webhook_url: "${ALERT_WEBHOOK_URL}"  # Slack/Discord/generic webhook URL
  channel: "generic"                    # slack, discord, or generic
  on_block: true
  on_hitl: true
  on_rate_limit: true
  on_injection: true
`
		}

		if err := os.WriteFile(path, []byte(content), 0600); err != nil {
			return fmt.Errorf("failed to write config: %w", err)
		}

		fmt.Printf("✅ Created %s\n", path)
		fmt.Println("  Edit the file to match your MCP servers and policies,")
		fmt.Println("  then run: mcp-guard serve --config " + path)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
	initCmd.Flags().StringVar(&templateFlag, "template", "", "template to use (github, postgres, slack, filesystem, generic)")
}
